global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "azure_blog_app"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - "daniel-blog-code-0ddbdmd2h3e8hxfq.westeurope-01.azurewebsites.net"
